// career-guide-frontend/src/App.vue
<template>
  <div class="min-h-screen flex flex-col">
    <header class="bg-blue-600 text-white p-4 shadow-md">
      <nav class="container mx-auto flex flex-wrap justify-between items-center gap-4">
        <router-link to="/" class="font-bold text-2xl">CareerGuide</router-link>
        <div class="flex flex-wrap gap-4">
          <router-link to="/login" class="hover:underline">Login</router-link>
          <router-link to="/register" class="hover:underline">Register</router-link>
          <router-link to="/quiz" class="hover:underline">Quiz</router-link>
          <router-link to="/results" class="hover:underline">Results</router-link>
          <router-link to="/career-pack" class="hover:underline">Career Pack</router-link>
          <router-link to="/jd-analyzer" class="hover:underline">JD Analyzer</router-link>
          <router-link to="/testimonials" class="hover:underline">Testimonials</router-link>
          <router-link to="/alumni" class="hover:underline">Alumni</router-link>
          <router-link to="/evidence" class="hover:underline">Evidence</router-link>
        </div>
      </nav>
    </header>
    <main class="flex-grow container mx-auto p-4">
      <router-view />
    </main>
    <footer class="bg-gray-200 p-4 text-center text-gray-600 text-sm">
      &copy; 2024 CareerGuide. All rights reserved.
    </footer>
  </div>
</template>

// src/App.tsx
import React from 'react'
import { BrowserRouter, Link } from 'react-router-dom'
import Routes from './routes'

export default function App() {
  return (
    <BrowserRouter>
      <div className="min-h-screen flex flex-col">
        <header className="bg-blue-600 text-white p-4 shadow-md">
          <nav className="container mx-auto flex flex-wrap gap-4 items-center justify-between">
            <Link to="/" className="font-bold text-2xl">Career Guide</Link>
            <div className="flex flex-wrap gap-4 text-sm">
              <Link to="/login" className="hover:underline">Login</Link>
              <Link to="/quiz" className="hover:underline">Quiz</Link>
              <Link to="/results" className="hover:underline">Results</Link>
              <Link to="/skills-analyzer" className="hover:underline">Skills</Link>
              <Link to="/about" className="hover:underline">About</Link>
              <Link to="/interview-kit" className="hover:underline">Interview Kit</Link>
            </div>
          </nav>
        </header>
        <main className="flex-grow container mx-auto p-4">
          <Routes />
        </main>
        <footer className="bg-gray-200 p-4 text-center text-gray-600 text-sm">&copy; 2024 CareerGuide</footer>
      </div>
    </BrowserRouter>
  )
}
